### PR TITLE
Support pluralization using messageformat.js

### PR DESCRIPTION
**Pull request by lephyrus**
This PR aims to add support for the ICU message format syntax with the help of messageformat.js. I tried to find a way of integrating this with the current ngx-translate framework in a minimally invasive way. Here's the idea:

* Extend `TranslateParser.interpolate()` to not only support string interpolation but also function interpolation: `interpolate(fn, params) => fn(params)`
* Add a new configurable `TranslateCompiler` component which allows pre-processing translation values. This is an optional step and does nothing by default.
* Add a `TranslateMessageFormatCompiler` which compiles the translation values (expected to use the ICU syntax) into interpolation functions using messageformat.js.

Corresponding issue: https://github.com/ngx-translate/core/issues/150

**Edit:** If the dependency on messageformat.js is a concern, `TranslateMessageFormatCompiler` could easily be pulled in as a separate package of course, same as the "loaders". Only the first two points above affect the core. I guess this comes down to how popular one expects the ICU syntax to be with ngx-translate users.

### CODE REVIEW

**Comment by santialbo** [comment]
Can we get some feedback from the project matainers? This PR is addressing a major concern for many of the library users and no one has said anything in 2 weeks.

**Comment by SamVerschueren** [comment]
I think it would be best to pull this in a separate package. People who don't need it shouldn't be dependent on messageformat. On mobile now so can't really dig in the code. I'll do my best to take a look in the coming days.

**Comment by lephyrus** [comment]
@ocombe  @SamVerschueren Not to appear impatient, but I have implemented what I consider to be a careful solution to an issue that was tagged with "help wanted". It's been 3 weeks without feedback - is there still interest in this at all?

**Comment by santialbo** [comment]
@lephyrus is there a way this could be pulled in a separate package somehow?

**Comment by ocombe** [comment]
@lephyrus yes, this would be a too big change for this lib, it should probably be in a separate package. If there's something that's missing in the lib to allow you to do that as an external package, it could be done, but I don't want to pull an external lib as a dependency like that

**Comment by lephyrus** [comment]
@ocombe Thanks for the feedback (and for this library). I've anticipated your concern, which is why I've already outlined in the description above that yes, the TranslateMessageFormatCompiler can be pulled in from a separate package. The first two points (function interpolation, compile step) affect the core, however. Since I've structured the commits accordingly, could you tell me if you'd be willing to merge the first two commits? I could then go about hosting the extra package.

**Comment by ocombe** [comment]
yes, the compiler part can be merged, it can be useful to other people who want to write extensions as well

**Comment by lephyrus** [comment]
@ocombe Ok, great. I do think the compiler in combination with allowing interpolation functions (not just interpolation strings) has a lot of potential.

I'll adapt the PR shortly.

**Comment by lephyrus** [comment]
@ocombe I have brought the PR up-to-date as per our discussion. I don't have the package for `TranslateMessageFormatCompiler` ready but I'm hoping you can add a link once it is and this has been released.

Note that I find type guarantees to be somewhat murky around translations - firstly because translation objects are of the `any` type, and secondly because `getValue()` is used both to retrieve translation values as well as translation parameters. Since that's already the way it's documented in the README, I've changed the return type of `getValue()` to `any`. Improving type safety would need a more substantial refactoring, in my opinion.

Finally, I wasn't quite sure where in the README to put the notes about the compiler. Feel free to change the documentation as you see fit.

**Comment by alexxxnf** [comment]
Any updates on this PR?

**Comment by lephyrus** [comment]
@alexxxnf From my perspective, the code is ready. But I'm certainly not going to invest the time to set up a separate package for `TranslateMessageFormatCompiler` unless this is merged. I can't force the maintainers to be responsive, nor do they have to accept contributions. 🤷‍♂️

**Comment by alexxxnf** [comment]
@lephyrus I got your point. We'll wait :)

**Comment by lephyrus** [comment]
I guess what we can do is ping @ocombe - it's been a while, after all.

**Comment by ocombe** [comment]
Yes sorry I was on holidays :)

**Comment by lephyrus** [comment]
@ocombe Well, that was quick. Sorry to hear the holidays are over though... :wink: I'll be in touch once I have a link to the compiler package.

**Comment by njulhb** [comment]
Hi @lephyrus , I find there is an issue that the strings are not compiled by the compiler when resource files are loaded slowly. I have found the root cause and submit a change in https://github.com/ngx-translate/core/pull/659. Could you please help me review the code change or fix the issue by yourself? 
I really need the fix in ngx-translate. 
Best Regards,
Haibo

**Comment by imfarhadk** [comment]
@lephyrus, any timeline to publish the NPM package for TranslateMessageFormatCompiler.

thanks
farhad

**Comment by lephyrus** [comment]
@imfarhadk I won't have time this weekend, but probably next. Let's say within two weeks from now. Knowing that some people want to use this helps, thanks.

**Comment by lephyrus** [comment]
I've published the package:
https://www.npmjs.com/package/ngx-translate-messageformat-compiler

It's my first NPM package, so let me know if something's wrong. Also, publishing a few lines of code as an Angular library really is insanely more complicated than it should be...

**Pull request merged**
