### PR TITLE
docs(README): Add plugin: MessageFormat Compiler

### PR DESCRIPTION
**Pull request by lephyrus**

### CODE REVIEW

**Comment by ocombe** [comment]
thanks!

**Comment by lephyrus** [comment]
@ocombe By the way, you may want to close https://github.com/ngx-translate/core/issues/150, even though it's hard to say what the exact expectation was there. But unless supporting more pluralization options is planned, I guess this is as good a time to close as any.

**Comment by ocombe** [comment]
Good idea; thanks

**Comment by Kranthi1547** [comment]
@lephyrus @ocombe Would you please update documentation/README providing examples to use pluralization with this merge

**Pull request merged**
