### PR TITLE
feat: upgrade to angular 15

### PR DESCRIPTION
**Pull request by riderx**
upgrade and build test with angular 15

### CODE REVIEW

**Review by Oneilos — APPROVED** [review]
Thanks, i need it too

**Comment by ocombe** [comment]
Why do you want to upgrade the project to v15? It should be working fine with v15 right now

**Comment by riderx** [comment]
nom in strict mode don't allow to install without it

**Review by gaewynn — APPROVED** [review]

**Comment by TiBz0u** [comment]
> npm in strict mode don't allow to install without it

Hi @riderx, even with this [peerDependency](https://github.com/ngx-translate/core/blob/5d04bd849876030b4117bf912a30c1a02a62df19/projects/ngx-translate/core/package.json#L22) that seems correct.
How do you trigger this error?

**Comment by riderx** [comment]
install latest nodejs 16 or 18 and latest npm, then npm i this in a angular 15 project and you got it

**Review by 1van0v — APPROVED** [review]

**Review by gaewynn — APPROVED** [review]

**Comment by jberndsen** [comment]
We experience the same Angular 15 npm restriction. What would it take to get this PR merged?

**Comment by matthiasferch** [comment]
Meanwhile, Angular 16 has been released and my team cannot upgrade because of our dependency on this plugin.

Is this repo still being maintained?

**Comment by riderx** [comment]
that will be compatible to v15 as well ?

**Comment by ocombe** [comment]
The current version is already compatible with v15... and I just tested, and it's also compatible with v16.
If you get an error about peer deps then you probably need to update npm because even with strict peer deps it works fine for me.

image

**Comment by ocombe** [comment]
@matthiasferch what error do you get with angular v16 and current ngx translate ?

**Comment by matthiasferch** [comment]
@ocombe 

```
Error: examples/showcase/src/app/app.module.ts:21:12 - error NG6002: 'TranslateModule' does not appear to be an NgModule class.

 21   imports: [
               ~
 22     CommonModule,
    ~~~~~~~~~~~~~~~~~
...
 32     AppRoutingModule,
    ~~~~~~~~~~~~~~~~~~~~~
 33   ],
    ~~~

  node_modules/@ngx-translate/core/public_api.d.ts:20:22
    20 export declare class TranslateModule {
                            ~~~~~~~~~~~~~~~
    This likely means that the library (@ngx-translate/core) which declares TranslateModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy. 
```
    
I'm on npm 8.15.0 and node 16.17.0.

**Comment by ocombe** [comment]
Since the current version has been built with v13 it is definitely compatible with ivy... usually this error happens when you install a library compatible with both ivy and the old view engine and you don't run ngcc on it, but since ngcc has been removed in v16, maybe it needs a new version of the lib in some cases ?

**Pull request closed without merging**
