### PR TITLE
add option to show keys and not translation

### PR DESCRIPTION
**Pull request by stefdelec**
- Allows users to see what is the key for a specific translation, in order to find quickly the value to change in .json
- My users have problem to find what key to change on our website. So they could add `window.desactivate_ngx_translate` in the console, and it would show keys and not translated values.

### CODE REVIEW

**Comment by lousley** [comment]
@stefdelec nothing...i have approved

**Comment by ocombe** [comment]
hello, the idea is interesting, but you should add documentation for that, and a test if possible

**Comment by balazsmaria** [comment]
why was this not merged?

**Comment by daco** [comment]
I got this functionality working by first reset all languages, doing something like:
`availableLanguages.forEach(lang => this.translateService.resetLang(lang))`
And then set the new language to a non existing key, for instance:
`this.translateService.use("key")`. 
Now make sure that your translation loader returns an Observable of {}. Now you'll see all the translation keys on your website.

**Pull request closed without merging**
