### PR TITLE
feat(service): add `getStreamOnTranslationChange` method

### PR DESCRIPTION
**Pull request by MKhowaja**
This is to fix the fact that the observable returned by the get method doesn't reactively update when translations change. We have an app that caches translations and makes a network call to retrieve more up to date translations but noticed that the observable doesn't emit the new translations.

### CODE REVIEW

**Comment by jrolheiser-va** [comment]
Did `stream()` not handle your use case?

**Comment by MKhowaja** [comment]
No it did not because its not the language that's changing but the translations when the backend call returns.

**Comment by MKhowaja** [comment]
Alternatively we could include onTranslationChange in the concat of stream

**Comment by XxAdi101xX** [comment]
We faced the same issue that @MKhowaja mentioned here and had to make some local fixes by using a wrapper functions to resolve it locally. This change would be super helpful.

**Comment by ocombe** [comment]
Hello, could you add a test, and update the README with the docs please?

**Comment by MKhowaja** [comment]
Yup!

**Comment by MKhowaja** [comment]
@ocombe  While I was writing the tests, I realized that this method doesn't update if the lang changes. Do you think there is value in changing this method so it reactively updates onLangChange events as well?

**Pull request merged**
